# Generated by Django 2.1.7 on 2019-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='is_actor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
